name: tuxtaskmanager
description: TuxTaskManager
version: 0.0.1
repository: https://github.com/vExcess/TuxTaskManager

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dcanvas:
    path: ./dcanvas
  drawlite:
    path: ./drawlite/dart

dev_dependencies:
  hotreloader: ^4.3.0
  lints: ^4.0.0
  test: ^1.24.0
