name: drawlite
description: A lightweight yet powerful cross platform graphics library inspired by Processing
version: 0.0.1
repository: https://github.com/librepaint/drawlite

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dcanvas:
    path: ../../dcanvas

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
